name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Criar e ativar ambiente virtual
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar e ativar ambiente virtual
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Verificar pytest
        run: |
          source venv/bin/activate
          pytest --version

      - name: Listar arquivos de teste
        run: ls -R

      - name: Rodar testes
        run: |
          source venv/bin/activate
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o Vercel CLI
        run: |
          npm install -g vercel

      - name: Deploy para Vercel
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
