name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install pytest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar testes
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Vercel CLI
        run: |
          curl -sL https://vercel.com/download -o vercel.tar.gz
          tar -xvzf vercel.tar.gz
          sudo mv vercel /usr/local/bin

      - name: Deploy para Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
  